#!/bin/bash


platform=""
if test `uname -m` = "arm64" 
then 
    platform="--platform=linux/amd64,linux/arm64"
    docker buildx create --use
fi

docker buildx build ${platform} \
    -t opendap/hyrax:snapshot \
    --build-arg OLFS_BRANCH="detectClientProtcolChange" \
    --build-arg HYRAX_DEPLOYMENT_CONTEXT=ROOT \
    --build-arg OLFS_BUILD_TARGET=ngap \
    --build-arg BES_FORCE=true \
    --build-arg OLFS_FORCE=true \
    hyrax-c7
